'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ERP_SIMS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Brands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Brands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_BrandsAndCategories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_BrandsAndCategories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Categories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Categories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_InventoryReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_InventoryReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Receiving() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Receiving", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Sales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Sales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Sales1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Sales1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_SaleScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_SaleScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_SalesReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_SalesReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_StockEntries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_StockEntries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Stocks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Stocks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActiveNavigationItem_Vendors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActiveNavigationItem_Vendors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Background_Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background_Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_EditTableSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_EditTableSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeBrand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeBrand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeCategory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeCategory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeCustomer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeCustomer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeSale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeSale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeStock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeStock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_MakeVendor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_MakeVendor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewBrand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewBrand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewCategory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewCategory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewCustomer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewCustomer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewSale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewSale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewStock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewStock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_NewVendor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_NewVendor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Restock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Restock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_SaveChanges() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_SaveChanges", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_SearchBarSearch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_SearchBarSearch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TableDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TableDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TableEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TableEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TableNewRow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TableNewRow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TablePageControlNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TablePageControlNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TablePageControlPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TablePageControlPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TableRowDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TableRowDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_TableView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_TableView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_ToPay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_ToPay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_ViewReceipt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_ViewReceipt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Checkbox_Checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checkbox_Checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Checkbox_Unchecked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checkbox_Unchecked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Brands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Brands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Categories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Categories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Entry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Entry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_InventoryReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_InventoryReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Receipt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Receipt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Sale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Sale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_SalesReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_SalesReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_StockEntries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_StockEntries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Stocks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Stocks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_Vendors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_Vendors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon_View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon_View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Image_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Image_ScreenBlackOpacity75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image_ScreenBlackOpacity75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Brands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Brands", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_BrandsAndCategories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_BrandsAndCategories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Categories() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Categories", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_InventoryReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_InventoryReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Receiving() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Receiving", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Sales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Sales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Sales1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Sales1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_SaleScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_SaleScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_SalesReport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_SalesReport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_StockEntries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_StockEntries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Stocks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Stocks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InactiveNavigationItem_Vendors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InactiveNavigationItem_Vendors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavigationHeadline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavigationHeadline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
